### ISSUE TITLE
Is a Windows version possible?

### ISSUE THREAD

**Issue by mgeier** [conda-forge/librsvg-feedstock#40]
There doesn't seem to be a Windows version of this package available on https://anaconda.org/conda-forge/librsvg.

Would it be possible to create a packages for Windows?

There seems to be a `win32` directory in the sources: https://gitlab.gnome.org/GNOME/librsvg/tree/master/win32

I'm not a Windows user myself, but I'm recommending `rsvg-convert` for my Sphinx extension (https://nbsphinx.readthedocs.io/en/0.5.0/markdown-cells.html#SVG-support-for-LaTeX) and I think it would be nice if this also worked for Windows users.

**Comment by pkgw** [comment]
Based on the Gitlab link you posted (thanks!), which has recent modifications, it definitely looks like a win32 build is possible.

Microsoft makes [free Windows VMs available](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) that can be used to work on this kind of stuff without the terrible cycle times that happen if you can only test using the CI frameworks. Would you be able to investigate getting a Windows build going in this way?

**Comment by mgeier** [comment]
Thanks for the quick response!

I have no clue about building stuff on Windows and honestly I don't have the time nor energy to tackle this.

But it would still be great if somebody else could do this!

In the meantime, I guess Windows users can use [Inkscape](https://anaconda.org/conda-forge/inkscape) as a (more bulky) replacement.
