### ISSUE TITLE
pre-unlink script failed for package

### ISSUE THREAD

**Issue by ngam** [conda-forge/librsvg-feedstock#82]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

```bash
Preparing transaction: done
Verifying transaction: done
Executing transaction: / WARNING conda.core.link:run_script(1228): pre-unlink script failed for package conda-forge/osx-arm64::librsvg-2.52.4-h957afdb_0
consider notifying the package maintainer
done
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ngam** [comment]
https://github.com/conda-forge/librsvg-feedstock/blob/4acf7dbcf4ce4070edca54cae8e7151bb5cf1fb4/recipe/pre-unlink.sh#L1-L7

**Comment by pkgw** [comment]
Thanks for reporting. Maybe the `rm` should just become an `rm -f`? Note that the `.so` extension is correct even on macOS.
